services:
  user-service:
    build:
      context: .
      dockerfile: ./deploy/docker/UserService.Dockerfile   
    ports: ["5001:8080"]
    environment:
      - ConnectionStrings__Default=Host=postgres-user;Port=5432;Database=uitgo_user;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=uit-go-redis:6379
      - Jwt__Secret=UltimateSuperSecretKeyForJwtTokenGeneration123
    depends_on: [postgres-user]

  driver-service:
    build:
      context: .
      dockerfile: ./deploy/docker/DriverService.Dockerfile 
    ports: ["5003:8080"]
    environment:
      - ConnectionStrings__Default=Host=postgres-driver;Port=5432;Database=uitgo_driver;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=uit-go-redis:6379
    depends_on: [postgres-driver]
    
  trip-service:
    build:
      context: .
      dockerfile: ./deploy/docker/TripService.Dockerfile   
    ports: ["5002:8080"]
    environment:
      - ConnectionStrings__Default=Host=postgres-trip;Port=5432;Database=uitgo_trip;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=uit-go-redis:6379
    depends_on: [postgres-trip, driver-service]

  

  api-gateway:
    build:
      context: .
      dockerfile: ./deploy/docker/ApiGateway.Dockerfile
    ports: ["8080:8080"]
    depends_on: [user-service, trip-service, driver-service]


  # gateway:
  #   build:
  #     context: ./gateway
  #     dockerfile: ./Nginx.Dockerfile  
  #   ports: ["8080:80"]
  #   depends_on: [user-service, trip-service, driver-service]


  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uitgo_user
    ports:
      - "5433:5432"
    volumes:
      - pg_user:/var/lib/postgresql/data

  postgres-trip:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uitgo_trip
    ports:
      - "5434:5432"
    volumes:
      - pg_trip:/var/lib/postgresql/data

  postgres-driver:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uitgo_driver
    ports:
      - "5435:5432"
    volumes:
      - pg_driver:/var/lib/postgresql/data
  
  uit-go-redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
    volumes: [ "redis-data:/data" ]

volumes:
  pg_user: {}
  pg_trip: {}
  pg_driver: {}
  redis-data: {}



